/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9ff",
        "on-surface": "#0b1c30",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "surface-container-low": "#eff4ff",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f8f9ff",
        "surface-variant": "#d3e4fe",
        "on-surface-variant": "#45464d",
        "primary": "#0f172a",
        "primary-container": "#131b2e",
        "on-primary": "#ffffff",
        "secondary": "#0058be",
        "secondary-container": "#2170e4",
        "on-secondary": "#ffffff",
        "tertiary": "#059669",
        "tertiary-container": "#002114",
        "tertiary-fixed": "#85f8c4",
        "on-tertiary-container": "#069669",
        "on-tertiary-fixed-variant": "#005137",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        "outline": "#76777d",
        "outline-variant": "#c6c6cd",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        headline: ["Outfit", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};

